### PR TITLE
Rename Boolean fields to provide standard isXXX getter

### PR DESCRIPTION
**Pull request by drekbour**
Rename resolving #42. I have a bunch of changes I would like to make (*) so am testing to see if PRs are accepted : )

(*) I actually did many refactorings years ago against hexameter but didn't share.

### CODE REVIEW

**Comment by adam-arold** [comment]
Hey, @drekbour I completely forgot about that issue! Thanks for fixing this! 🎉 What other changes do you have in mind? *(you can merge this one)*

**Comment by drekbour** [comment]
perf items and further generalisations (notably not requiring SatelliteData at all). I'll add to this 'using kotlin' (which is why I want a java sample so I don't unknowingly break the api). I'll try to group these up and PR sequentially. First up is figuring out how to write a JMH test in kotlin+gradle.

**Comment by adam-arold** [comment]
What's a JMH test?

**Comment by drekbour** [comment]
http://tutorials.jenkov.com/java-performance/jmh.html

**Comment by adam-arold** [comment]
Hah, never tried it so far! Sounds interesting. So I approved this PR, you can merge it if you want!

**Comment by drekbour** [comment]
I don't have a merge option anywhere.

**Comment by adam-arold** [comment]
Weird. I merged it though!

**Pull request merged**
